# Generated by Django 3.2.2 on 2023-01-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdetails',
            fields=[
                ('cust_id', models.CharField(blank=True, max_length=15, null=True)),
                ('booking_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=11, null=True)),
                ('vehicle_id', models.CharField(blank=True, max_length=17, null=True)),
                ('vehicle_status', models.CharField(blank=True, max_length=14, null=True)),
                ('meter_reading', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookingdetails',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Vehicledetails',
        ),
    ]
