# Generated by Django 3.2.2 on 2023-01-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230122_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bill_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('booking_id', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=9, null=True)),
                ('amount_paid', models.BigIntegerField(blank=True, null=True)),
                ('tax_amount', models.BigIntegerField(blank=True, null=True)),
                ('total_amount', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing',
                'managed': False,
            },
        ),
    ]
